// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Identifies key qualities of a product given product information using AI.
 *
 * - identifyKeyQualities - A function that handles the identification of key qualities.
 * - IdentifyKeyQualitiesInput - The input type for the identifyKeyQualities function.
 * - IdentifyKeyQualitiesOutput - The return type for the identifyKeyQualities function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const IdentifyKeyQualitiesInputSchema = z.object({
  productName: z.string().describe('The name of the product.'),
  productDescription: z.string().describe('The full description of the product.'),
  customerReviews: z.string().describe('Customer reviews for the product.'),
});

export type IdentifyKeyQualitiesInput = z.infer<typeof IdentifyKeyQualitiesInputSchema>;

const IdentifyKeyQualitiesOutputSchema = z.object({
  keyQualities: z
    .array(z.string())
    .describe('An array of key qualities or features to highlight in the product description.'),
});

export type IdentifyKeyQualitiesOutput = z.infer<typeof IdentifyKeyQualitiesOutputSchema>;

export async function identifyKeyQualities(input: IdentifyKeyQualitiesInput): Promise<IdentifyKeyQualitiesOutput> {
  return identifyKeyQualitiesFlow(input);
}

const prompt = ai.definePrompt({
  name: 'identifyKeyQualitiesPrompt',
  input: {schema: IdentifyKeyQualitiesInputSchema},
  output: {schema: IdentifyKeyQualitiesOutputSchema},
  prompt: `You are an expert marketing copywriter.

  Given the following product information, identify the key qualities or features to highlight in the product description.
  Return them as a JSON array of strings.

  Product Name: {{{productName}}}
  Product Description: {{{productDescription}}}
  Customer Reviews: {{{customerReviews}}}`,
});

const identifyKeyQualitiesFlow = ai.defineFlow(
  {
    name: 'identifyKeyQualitiesFlow',
    inputSchema: IdentifyKeyQualitiesInputSchema,
    outputSchema: IdentifyKeyQualitiesOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
