// This file is generated by Firebase Genkit.
'use server';

/**
 * @fileOverview A flow to suggest relevant keywords for products to improve searchability and discoverability.
 *
 * - suggestProductKeywords - A function that handles the keyword suggestion process.
 * - SuggestProductKeywordsInput - The input type for the suggestProductKeywords function.
 * - SuggestProductKeywordsOutput - The return type for the suggestProductKeywords function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestProductKeywordsInputSchema = z.object({
  productName: z.string().describe('The name of the product.'),
  productDescription: z.string().describe('The description of the product.'),
});
export type SuggestProductKeywordsInput = z.infer<typeof SuggestProductKeywordsInputSchema>;

const SuggestProductKeywordsOutputSchema = z.object({
  keywords: z
    .array(z.string())
    .describe('An array of relevant keywords for the product.'),
});
export type SuggestProductKeywordsOutput = z.infer<typeof SuggestProductKeywordsOutputSchema>;

export async function suggestProductKeywords(input: SuggestProductKeywordsInput): Promise<SuggestProductKeywordsOutput> {
  return suggestProductKeywordsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestProductKeywordsPrompt',
  input: {schema: SuggestProductKeywordsInputSchema},
  output: {schema: SuggestProductKeywordsOutputSchema},
  prompt: `You are an expert in e-commerce SEO and product discoverability.
  Your task is to suggest relevant keywords for a given product based on its name and description.
  Provide an array of keywords that will help improve the product's searchability in an online store.

  Product Name: {{{productName}}}
  Product Description: {{{productDescription}}}

  Keywords:`, // Ensure the AI returns a comma separated list of keywords
});

const suggestProductKeywordsFlow = ai.defineFlow(
  {
    name: 'suggestProductKeywordsFlow',
    inputSchema: SuggestProductKeywordsInputSchema,
    outputSchema: SuggestProductKeywordsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
