import type { Product } from '@/types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Elegant Smartwatch X1',
    description: 'Stay connected and stylish with the Smartwatch X1. Features heart rate monitoring, GPS, and a vibrant AMOLED display.',
    baseDescription: 'A smartwatch with multiple features.',
    price: 199.99,
    images: ['https://placehold.co/600x400.png?text=Smartwatch+Front', 'https://placehold.co/600x400.png?text=Smartwatch+Side', 'https://placehold.co/600x400.png?text=Smartwatch+Screen'],
    category: 'Electronics',
    rating: 4.5,
    stock: 50,
  },
  {
    id: '2',
    name: 'Luxury Silk Scarf',
    description: 'Wrap yourself in luxury with this 100% pure silk scarf. Hand-painted design, perfect for any occasion.',
    baseDescription: 'A beautiful silk scarf.',
    price: 79.50,
    images: ['https://placehold.co/600x400.png?text=Scarf+Folded', 'https://placehold.co/600x400.png?text=Scarf+Detail', 'https://placehold.co/600x400.png?text=Scarf+Worn'],
    category: 'Clothing',
    rating: 4.8,
    stock: 120,
  },
  {
    id: '3',
    name: '"The Cosmic Labyrinth" - Sci-Fi Novel',
    description: 'Embark on an epic journey through space in this bestselling sci-fi novel. A tale of adventure, mystery, and hope.',
    baseDescription: 'A science fiction book.',
    price: 14.99,
    images: ['https://placehold.co/600x400.png?text=Book+Cover', 'https://placehold.co/600x400.png?text=Book+Spine'],
    category: 'Books',
    rating: 4.2,
    stock: 200,
  },
  {
    id: '4',
    name: 'Gourmet Coffee Maker Pro',
    description: 'Brew the perfect cup every time with the Gourmet Coffee Maker Pro. Features programmable settings and a built-in grinder.',
    baseDescription: 'A programmable coffee maker.',
    price: 129.00,
    images: ['https://placehold.co/600x400.png?text=Coffee+Maker+Main', 'https://placehold.co/600x400.png?text=Coffee+Maker+Carafe'],
    category: 'Home & Kitchen',
    rating: 4.6,
    stock: 75,
  },
  {
    id: '5',
    name: 'Professional Yoga Mat',
    description: 'Enhance your practice with our eco-friendly, non-slip yoga mat. Provides excellent cushioning and support.',
    baseDescription: 'A high-quality yoga mat.',
    price: 45.00,
    images: ['https://placehold.co/600x400.png?text=Yoga+Mat+Rolled', 'https://placehold.co/600x400.png?text=Yoga+Mat+Unrolled'],
    category: 'Sports & Outdoors',
    rating: 4.9,
    stock: 150,
  },
  {
    id: '6',
    name: 'Wireless Noise-Cancelling Headphones',
    description: 'Immerse yourself in sound with these premium wireless headphones. Active noise cancellation and 30-hour battery life.',
    baseDescription: 'Headphones with noise cancelling.',
    price: 249.99,
    images: ['https://placehold.co/600x400.png?text=Headphones+Main', 'https://placehold.co/600x400.png?text=Headphones+Earcup'],
    category: 'Electronics',
    rating: 4.7,
    stock: 80,
  },
  {
    id: '7',
    name: 'Organic Cotton T-Shirt',
    description: 'Comfortable and sustainable, this t-shirt is made from 100% organic cotton. Soft, breathable, and ethically sourced.',
    baseDescription: 'A basic cotton t-shirt.',
    price: 29.95,
    images: ['https://placehold.co/600x400.png?text=T-shirt+Front', 'https://placehold.co/600x400.png?text=T-shirt+Fabric'],
    category: 'Clothing',
    rating: 4.4,
    stock: 300,
  },
  {
    id: '8',
    name: 'The Art of Mindful Cooking',
    description: 'Discover delicious recipes and the joy of cooking with mindfulness. Beautifully illustrated cookbook.',
    baseDescription: 'A cookbook about mindful cooking.',
    price: 22.50,
    images: ['https://placehold.co/600x400.png?text=Cookbook+Cover', 'https://placehold.co/600x400.png?text=Cookbook+Spread'],
    category: 'Books',
    rating: 4.6,
    stock: 90,
  },
];
