
import type { Product, Review } from '@/types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Elegant Smartwatch X1',
    description: 'Stay connected and stylish with the Smartwatch X1. Features heart rate monitoring, GPS, and a vibrant AMOLED display.',
    baseDescription: 'A smartwatch with multiple features.',
    price: 199.99,
    images: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
    category: 'Electronics',
    rating: 4.5,
    stock: 50,
  },
  {
    id: '2',
    name: 'Luxury Silk Scarf',
    description: 'Wrap yourself in luxury with this 100% pure silk scarf. Hand-painted design, perfect for any occasion.',
    baseDescription: 'A beautiful silk scarf.',
    price: 79.50,
    images: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
    category: 'Clothing',
    rating: 4.8,
    stock: 120,
  },
  {
    id: '3',
    name: '"The Cosmic Labyrinth" - Sci-Fi Novel',
    description: 'Embark on an epic journey through space in this bestselling sci-fi novel. A tale of adventure, mystery, and hope.',
    baseDescription: 'A science fiction book.',
    price: 14.99,
    images: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
    category: 'Books',
    rating: 4.2,
    stock: 200,
  },
  {
    id: '4',
    name: 'Gourmet Coffee Maker Pro',
    description: 'Brew the perfect cup every time with the Gourmet Coffee Maker Pro. Features programmable settings and a built-in grinder.',
    baseDescription: 'A programmable coffee maker.',
    price: 129.00,
    images: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
    category: 'Home & Kitchen',
    rating: 4.6,
    stock: 75,
  },
  {
    id: '5',
    name: 'Professional Yoga Mat',
    description: 'Enhance your practice with our eco-friendly, non-slip yoga mat. Provides excellent cushioning and support.',
    baseDescription: 'A high-quality yoga mat.',
    price: 45.00,
    images: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
    category: 'Sports & Outdoors',
    rating: 4.9,
    stock: 150,
  },
  {
    id: '6',
    name: 'Wireless Noise-Cancelling Headphones',
    description: 'Immerse yourself in sound with these premium wireless headphones. Active noise cancellation and 30-hour battery life.',
    baseDescription: 'Headphones with noise cancelling.',
    price: 249.99,
    images: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
    category: 'Electronics',
    rating: 4.7,
    stock: 80,
  },
  {
    id: '7',
    name: 'Organic Cotton T-Shirt',
    description: 'Comfortable and sustainable, this t-shirt is made from 100% organic cotton. Soft, breathable, and ethically sourced.',
    baseDescription: 'A basic cotton t-shirt.',
    price: 29.95,
    images: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
    category: 'Clothing',
    rating: 4.4,
    stock: 300,
  },
  {
    id: '8',
    name: 'The Art of Mindful Cooking',
    description: 'Discover delicious recipes and the joy of cooking with mindfulness. Beautifully illustrated cookbook.',
    baseDescription: 'A cookbook about mindful cooking.',
    price: 22.50,
    images: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
    category: 'Books',
    rating: 4.6,
    stock: 90,
  },
];

export const mockReviews: Review[] = [
  {
    id: 'review1',
    productId: '1',
    author: 'Alice Wonderland',
    rating: 5,
    comment: 'Absolutely love this smartwatch! The display is crisp and the features are amazing. Battery life is decent too.',
    date: '2024-05-10',
    avatarUrl: 'https://placehold.co/40x40.png?text=AW'
  },
  {
    id: 'review2',
    productId: '1',
    author: 'Bob The Builder',
    rating: 4,
    comment: 'Great watch, very functional. Sometimes the GPS takes a moment to connect, but overall very satisfied.',
    date: '2024-05-15',
    avatarUrl: 'https://placehold.co/40x40.png?text=BT'
  },
  {
    id: 'review3',
    productId: '2',
    author: 'Charlie Brown',
    rating: 5,
    comment: 'The silk scarf is even more beautiful in person. The colors are vibrant and the material feels luxurious.',
    date: '2024-04-20',
  },
  {
    id: 'review4',
    productId: '4',
    author: 'Diana Prince',
    rating: 4,
    comment: 'Makes a great cup of coffee! The grinder is a bit loud, but it\'s worth it for fresh beans.',
    date: '2024-05-01',
    avatarUrl: 'https://placehold.co/40x40.png?text=DP'
  },
  {
    id: 'review5',
    productId: '4',
    author: 'Edward Scissorhands',
    rating: 5,
    comment: 'Best coffee maker I\'ve owned. Programmable features are super convenient for my morning routine.',
    date: '2024-05-22',
  },
   {
    id: 'review6',
    productId: '1',
    author: 'Fiona Gallagher',
    rating: 3,
    comment: 'It\'s an okay smartwatch. Does the job but didn\'t wow me. The strap feels a bit cheap for the price.',
    date: '2024-06-01',
  },
];
